In [1]:
import pandas as pd
import numpy as np

In [2]:
btc = pd.read_csv('btc.csv')

In [4]:
aux = btc['Open'].values

In [6]:
aux.reshape((-1,1))

array([[ 9837.  ],
       [ 9889.95],
       [ 9880.05],
       ...,
       [57544.83],
       [57544.91],
       [57538.68]])

In [7]:
import pandas as pd
import numpy as np
import keras
import tensorflow as tf
from keras.preprocessing.sequence import TimeseriesGenerator

In [21]:
btc.iloc[btc.shape[0]//2:]

,Unnamed: 0,Unix timestamp,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
179212,179212,1566181500000,10390.68,10396.67,10377.92,10379.85,75.206841,7.809919e+05,696,18.830949,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,626.100694
179213,179213,1566181800000,10379.85,10414.00,10377.92,10406.87,74.043090,7.696033e+05,1020,44.041439,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,626.104167
179214,179214,1566182100000,10408.94,10439.99,10405.08,10419.20,212.081638,2.210167e+06,1772,145.894183,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,626.107639
179215,179215,1566182400000,10419.18,10422.21,10405.00,10405.00,85.357869,8.890789e+05,801,24.062799,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,626.111111
179216,179216,1566182700000,10405.94,10420.25,10396.96,10417.74,134.874635,1.404320e+06,902,91.617825,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,626.114583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358420,358420,1620069900000,57496.61,57570.89,57490.12,57540.07,137.526668,7.912052e+06,5387,69.355946,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1249.809028
358421,358421,1620070200000,57540.07,57600.00,57506.46,57544.54,144.666322,8.324256e+06,5606,77.965072,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1249.812500
358422,358422,1620070500000,57544.83,57562.95,57469.53,57544.92,136.014959,7.824070e+06,5459,63.236847,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1249.815972
358423,358423,1620070800000,57544.91,57579.96,57489.79,57538.69,109.809575,6.318464e+06,5256,56.967127,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1249.819444
358424,358424,1620071100000,57538.68,57538.69,57466.57,57508.99,58.930195,3.387942e+06,2900,31.694176,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1249.822917

In [52]:
y_test =  btc['Close'].iloc[(btc.shape[0]//2):].values

In [54]:
y_test.reshape((-1,1))

array([[10379.85],
       [10406.87],
       [10419.2 ],
       ...,
       [57544.92],
       [57538.69],
       [57508.99]])

In [13]:
train_generator = TimeseriesGenerator(btc.iloc[:btc.shape[0]//2], btc['Close'].iloc[:btc.shape[0]//2], length=15, batch_size=20)

In [55]:
test_generator = TimeseriesGenerator(btc.iloc[(btc.shape[0]//2):], y_test.reshape((-1,1)), length=15, batch_size = 1)

In [50]:
test_generator.targets

179212    10379.85
179213    10406.87
179214    10419.20
179215    10405.00
179216    10417.74
            ...
358420    57540.07
358421    57544.54
358422    57544.92
358423    57538.69
358424    57508.99
Name: Close, Length: 179213, dtype: float64

In [16]:
from keras.models import Sequential
from keras.layers import LSTM, Dense

model = Sequential()
model.add(
    LSTM(10,
        activation='relu',
        input_shape=(15, len(btc.columns)))
)
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

num_epochs = 25
model.fit_generator(train_generator, epochs=20, verbose=1)

Epoch 1/20
8960/8960 [==============================] - 83s 9ms/step - loss: nan
Epoch 2/20
8960/8960 [==============================] - 80s 9ms/step - loss: nan
Epoch 3/20
8960/8960 [==============================] - 83s 9ms/step - loss: nan
Epoch 4/20
8960/8960 [==============================] - ETA: 0s - loss: n - 82s 9ms/step - loss: nan
Epoch 5/20
8960/8960 [==============================] - 81s 9ms/step - loss: nan
Epoch 6/20
8960/8960 [==============================] - 78s 9ms/step - loss: nan
Epoch 7/20
8960/8960 [==============================] - 82s 9ms/step - loss: nan
Epoch 8/20
8960/8960 [==============================] - 79s 9ms/step - loss: nan
Epoch 9/20
8960/8960 [==============================] - 77s 9ms/step - loss: nan
Epoch 10/20
8960/8960 [==============================] - 81s 9ms/step - loss: nan
Epoch 11/20
8960/8960 [==============================] - 84s 9ms/step - loss: nan
Epoch 12/20
8960/8960 [==============================] - 82s 9ms/step - loss: nan
Epoch 13/20
8960/8960 [==============================] - 82s 9ms/step - loss: nan 0s -
Epoch 14/20
8960/8960 [==============================] - 83s 9ms/step - loss: nan
Epoch 15/20
8960/8960 [==============================] - 84s 9ms/step - loss: nan
Epoch 16/20
8960/8960 [==============================] - 83s 9ms/step - loss: nan
Epoch 17/20
8960/8960 [==============================] - 81s 9ms/step - loss: nan 0s
Epoch 18/20
8960/8960 [==============================] - 82s 9ms/step - loss: nan
Epoch 19/20
8960/8960 [==============================] - 82s 9ms/step - loss: nan
Epoch 20/20
8960/8960 [==============================] - 83s 9ms/step - loss: nan

In [58]:
pred = model.predict(test_generator, verbose=1)

179198/179198 [==============================] - 290s 2ms/step

# ada = pd.read_csv('ada.csv')

In [511]:
ada.shape

(318812, 73)

In [512]:
btc.shape

(358425, 73)

In [513]:
btc.head(5)

,Unnamed: 0,Unix timestamp,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
0,0,1512086400000,9837.00,9889.95,9712.00,9889.95,18.837786,185001.274233,148,12.786414,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,1,1512086700000,9889.95,9900.03,9840.04,9880.05,18.657750,184495.212054,163,10.060344,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003472
2,2,1512087000000,9880.05,9900.01,9871.13,9894.96,18.854311,186422.750037,98,11.785809,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006944
3,3,1512087300000,9894.89,9894.89,9850.00,9871.44,22.392083,221373.067131,112,19.404541,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.010417
4,4,1512087600000,9850.01,9871.44,9800.00,9828.89,24.735934,243242.730930,152,12.047246,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.013889

In [514]:
ada.head(5)

,Unnamed: 0,Unix timestamp,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
0,0,1523937600000,0.25551,0.27000,0.25551,0.26666,268613.33,70602.884982,77,209583.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,1,1523937900000,0.26700,0.28800,0.26121,0.26696,1278878.30,342194.004025,567,410305.16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003472
2,2,1523938200000,0.26698,0.28134,0.26389,0.26709,1372572.09,367736.101426,733,385452.37,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006944
3,3,1523938500000,0.26708,0.26869,0.26208,0.26331,977324.75,260132.114090,437,251076.69,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.010417
4,4,1523938800000,0.26331,0.26436,0.26008,0.26290,887698.10,232282.163354,591,429640.80,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.013889

In [515]:
ind_min = 0

while btc['Unix timestamp'][ind_min] < ada['Unix timestamp'][0]:
    ind_min += 1

In [516]:
ind_min

39057

In [517]:
btc = btc.tail(btc.shape[0]-ind_min)

In [518]:
btc = btc.reset_index(drop=True)

In [519]:
btc

,Unnamed: 0,Unix timestamp,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
0,39057,1523937600000,8049.90,8049.90,8024.00,8032.99,148.245567,1.191060e+06,637,70.516715,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.166667
1,39058,1523937900000,8033.00,8034.80,8024.21,8032.95,60.944816,4.894450e+05,406,37.350873,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.170139
2,39059,1523938200000,8032.95,8032.95,8010.01,8015.00,79.428218,6.371818e+05,639,42.065398,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.173611
3,39060,1523938500000,8015.00,8024.80,8000.00,8007.00,134.520342,1.078367e+06,697,65.886986,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.177083
4,39061,1523938800000,8007.01,8019.99,8001.37,8010.99,51.748348,4.145381e+05,463,22.759268,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,137.180556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319363,358420,1620069900000,57496.61,57570.89,57490.12,57540.07,137.526668,7.912052e+06,5387,69.355946,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1249.809028
319364,358421,1620070200000,57540.07,57600.00,57506.46,57544.54,144.666322,8.324256e+06,5606,77.965072,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1249.812500
319365,358422,1620070500000,57544.83,57562.95,57469.53,57544.92,136.014959,7.824070e+06,5459,63.236847,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1249.815972
319366,358423,1620070800000,57544.91,57579.96,57489.79,57538.69,109.809575,6.318464e+06,5256,56.967127,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1249.819444
319367,358424,1620071100000,57538.68,57538.69,57466.57,57508.99,58.930195,3.387942e+06,2900,31.694176,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1249.822917

In [520]:
ada

,Unnamed: 0,Unix timestamp,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
0,0,1523937600000,0.25551,0.27000,0.25551,0.26666,268613.33,70602.884982,77,209583.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,1,1523937900000,0.26700,0.28800,0.26121,0.26696,1278878.30,342194.004025,567,410305.16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003472
2,2,1523938200000,0.26698,0.28134,0.26389,0.26709,1372572.09,367736.101426,733,385452.37,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006944
3,3,1523938500000,0.26708,0.26869,0.26208,0.26331,977324.75,260132.114090,437,251076.69,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.010417
4,4,1523938800000,0.26331,0.26436,0.26008,0.26290,887698.10,232282.163354,591,429640.80,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.013889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,318807,1619903100000,1.33790,1.33810,1.33610,1.33700,303316.52,405653.768865,731,121599.65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.711806
318808,318808,1619903400000,1.33700,1.33740,1.33400,1.33570,403303.33,538749.725321,797,132133.12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.715278
318809,318809,1619903700000,1.33550,1.33590,1.33150,1.33190,374242.62,499010.296564,1013,146257.71,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.718750
318810,318810,1619904000000,1.33190,1.33320,1.33000,1.33280,529332.55,704819.153364,1251,301902.33,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.722222
318811,318811,1619904300000,1.33280,1.33460,1.33250,1.33450,133120.72,177509.742627,246,82977.88,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.725694

In [521]:
i = 0
ada_spec = []

for i in range(1, ada.shape[0]):
    if ada['Unix timestamp'][i] - ada['Unix timestamp'][i-1] != 300000:
        print(i)
        ada_spec.append(i)

20136
20436
22280
53072
60470
94370
112742
119465
139094
164918
168346
190210
193194
197129
211991
230393
275039
281173
282133
295966
302554
315496
316931

In [522]:
i = 0
btc_spec = []

for i in range(1, btc.shape[0]):
    if btc['Unix timestamp'][i] - btc['Unix timestamp'][i-1] != 300000:
        print(i)
        btc_spec.append(i)

20136
20436
22280
53072
60470
94370
112742
119465
139094
164918
168346
190210
193194
197129
211991
230393
275039
281173
282133
295966
302554
315496
316931

In [523]:
btc.loc[btc_spec[0]-2:btc_spec[0]+3]

,Unnamed: 0,Unix timestamp,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
20134,59191,1529977800000,6226.99,6230.00,6223.00,6230.00,40.252165,2.506784e+05,447,24.857528,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,207.076389
20135,59192,1529978100000,6232.45,6232.45,6223.01,6227.99,24.978445,1.555444e+05,345,13.387124,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,207.079861
20136,59193,1530014400000,6228.00,6228.00,6180.00,6195.46,196.104885,1.215623e+06,910,109.254036,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,207.500000
20137,59194,1530014700000,6195.00,6217.90,6192.07,6212.98,301.565995,1.872265e+06,1143,133.625621,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,207.503472
20138,59195,1530015000000,6211.00,6217.89,6208.09,6216.78,97.978986,6.088265e+05,728,54.312132,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,207.506944
20139,59196,1530015300000,6212.36,6217.37,6209.99,6214.40,93.996499,5.840293e+05,629,53.707696,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,207.510417

In [524]:
ada.loc[ada_spec[0]-2:ada_spec[0]+3]

,Unnamed: 0,Unix timestamp,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
20134,20134,1529977800000,0.13334,0.13349,0.13301,0.13305,463754.9,61761.767366,87,295985.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,69.909722
20135,20135,1529978100000,0.13322,0.13339,0.13300,0.13308,220595.4,29355.936249,43,53108.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,69.913194
20136,20136,1530014400000,0.13307,0.13307,0.13153,0.13174,484820.5,64021.480054,161,221451.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.333333
20137,20137,1530014700000,0.13175,0.13242,0.13165,0.13220,279483.5,36910.271600,75,120954.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.336806
20138,20138,1530015000000,0.13229,0.13229,0.13182,0.13221,450564.5,59579.334172,101,246586.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.340278
20139,20139,1530015300000,0.13196,0.13216,0.13154,0.13154,293935.0,38754.834619,59,109268.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.343750

In [525]:
btc = btc.head(ada.shape[0])

In [526]:
btc.columns[0:11]

Index(['Unnamed: 0', 'Unix timestamp', 'Open', 'High', 'Low', 'Close',
       'Volume', 'Quote asset volume', 'Number of trades',
       'Taker buy base asset volume', 'Taker buy quote asset volumne'],
      dtype='object')

In [527]:
ada = ada.drop('Unnamed: 0', axis = 1)
btc = btc.drop('Unnamed: 0', axis = 1)

In [528]:
ada = ada.drop('Unix timestamp', axis = 1)
btc = btc.drop('Unix timestamp', axis = 1)

In [529]:
btc.columns[0:9]

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Quote asset volume',
       'Number of trades', 'Taker buy base asset volume',
       'Taker buy quote asset volumne'],
      dtype='object')

In [530]:
for name in btc.columns[0:9]:
    btc = btc.rename(columns={name: 'BTC ' + name})

In [531]:
btc.columns[0:9]

Index(['BTC Open', 'BTC High', 'BTC Low', 'BTC Close', 'BTC Volume',
       'BTC Quote asset volume', 'BTC Number of trades',
       'BTC Taker buy base asset volume', 'BTC Taker buy quote asset volumne'],
      dtype='object')

In [532]:
btc.columns[9:]

Index(['Year', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Jan', 'Feb',
       'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
       '0h', '1h', '2h', '3h', '4h', '5h', '6h', '7h', '8h', '9h', '10h',
       '11h', '12h', '13h', '14h', '15h', '16h', '17h', '18h', '19h', '20h',
       '21h', '22h', '23h', 'Week1', 'Week2', 'Week3', 'Week4', 'Week5', '0m',
       '5m', '10m', '15m', '20m', '25m', '30m', '35m', '40m', '45m', '50m',
       '55m', 'Time/days'],
      dtype='object')

In [533]:
for col in btc.columns[9:]:
    btc = btc.drop(col, axis = 1)

In [534]:
btc

,BTC Open,BTC High,BTC Low,BTC Close,BTC Volume,BTC Quote asset volume,BTC Number of trades,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne
0,8049.90,8049.90,8024.00,8032.99,148.245567,1.191060e+06,637,70.516715,5.664891e+05
1,8033.00,8034.80,8024.21,8032.95,60.944816,4.894450e+05,406,37.350873,2.999910e+05
2,8032.95,8032.95,8010.01,8015.00,79.428218,6.371818e+05,639,42.065398,3.374793e+05
3,8015.00,8024.80,8000.00,8007.00,134.520342,1.078367e+06,697,65.886986,5.283480e+05
4,8007.01,8019.99,8001.37,8010.99,51.748348,4.145381e+05,463,22.759268,1.823459e+05
...,...,...,...,...,...,...,...,...,...
318807,57659.88,57673.17,57608.33,57657.75,77.757069,4.482218e+06,3466,34.401756,1.982985e+06
318808,57657.75,57686.57,57650.01,57675.00,119.218784,6.875150e+06,4052,51.587597,2.974936e+06
318809,57674.99,57684.21,57525.00,57540.40,88.831368,5.116978e+06,4682,36.346760,2.094020e+06
318810,57540.40,57595.72,57498.56,57578.08,109.076746,6.275271e+06,4631,39.890115,2.295065e+06
318811,57576.01,57614.06,57546.31,57597.17,81.945281,4.718366e+06,4336,34.198034,1.969175e+06

In [535]:
btc.columns[:4]

Index(['BTC Open', 'BTC High', 'BTC Low', 'BTC Close'], dtype='object')

In [536]:
btc_hl_co = (btc['BTC High'] - btc['BTC Low'])/(btc['BTC Close'] - btc['BTC Open'])

In [537]:
btc.insert(4, 'BTC HL/CO', btc_hl_co)

In [538]:
btc

,BTC Open,BTC High,BTC Low,BTC Close,BTC HL/CO,BTC Volume,BTC Quote asset volume,BTC Number of trades,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne
0,8049.90,8049.90,8024.00,8032.99,-1.531638,148.245567,1.191060e+06,637,70.516715,5.664891e+05
1,8033.00,8034.80,8024.21,8032.95,-211.800000,60.944816,4.894450e+05,406,37.350873,2.999910e+05
2,8032.95,8032.95,8010.01,8015.00,-1.277994,79.428218,6.371818e+05,639,42.065398,3.374793e+05
3,8015.00,8024.80,8000.00,8007.00,-3.100000,134.520342,1.078367e+06,697,65.886986,5.283480e+05
4,8007.01,8019.99,8001.37,8010.99,4.678392,51.748348,4.145381e+05,463,22.759268,1.823459e+05
...,...,...,...,...,...,...,...,...,...,...
318807,57659.88,57673.17,57608.33,57657.75,-30.441315,77.757069,4.482218e+06,3466,34.401756,1.982985e+06
318808,57657.75,57686.57,57650.01,57675.00,2.119420,119.218784,6.875150e+06,4052,51.587597,2.974936e+06
318809,57674.99,57684.21,57525.00,57540.40,-1.182926,88.831368,5.116978e+06,4682,36.346760,2.094020e+06
318810,57540.40,57595.72,57498.56,57578.08,2.578556,109.076746,6.275271e+06,4631,39.890115,2.295065e+06
318811,57576.01,57614.06,57546.31,57597.17,3.201796,81.945281,4.718366e+06,4336,34.198034,1.969175e+06

In [539]:
norm_col = btc.columns[:4]

In [540]:
norm_col

Index(['BTC Open', 'BTC High', 'BTC Low', 'BTC Close'], dtype='object')

In [541]:
btc['BTC Open'].shift(1)

0              NaN
1          8049.90
2          8033.00
3          8032.95
4          8015.00
            ...
318807    57680.00
318808    57659.88
318809    57657.75
318810    57674.99
318811    57540.40
Name: BTC Open, Length: 318812, dtype: float64

In [542]:
for col in norm_col:
    btc.insert(len(btc.columns), col + ' Ratio', btc[col]/btc[col].shift(1))

In [543]:
btc

,BTC Open,BTC High,BTC Low,BTC Close,BTC HL/CO,BTC Volume,BTC Quote asset volume,BTC Number of trades,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio
0,8049.90,8049.90,8024.00,8032.99,-1.531638,148.245567,1.191060e+06,637,70.516715,5.664891e+05,NaN,NaN,NaN,NaN
1,8033.00,8034.80,8024.21,8032.95,-211.800000,60.944816,4.894450e+05,406,37.350873,2.999910e+05,0.997901,0.998124,1.000026,0.999995
2,8032.95,8032.95,8010.01,8015.00,-1.277994,79.428218,6.371818e+05,639,42.065398,3.374793e+05,0.999994,0.999770,0.998230,0.997765
3,8015.00,8024.80,8000.00,8007.00,-3.100000,134.520342,1.078367e+06,697,65.886986,5.283480e+05,0.997765,0.998985,0.998750,0.999002
4,8007.01,8019.99,8001.37,8010.99,4.678392,51.748348,4.145381e+05,463,22.759268,1.823459e+05,0.999003,0.999401,1.000171,1.000498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,57659.88,57673.17,57608.33,57657.75,-30.441315,77.757069,4.482218e+06,3466,34.401756,1.982985e+06,0.999651,0.999743,1.001482,0.999963
318808,57657.75,57686.57,57650.01,57675.00,2.119420,119.218784,6.875150e+06,4052,51.587597,2.974936e+06,0.999963,1.000232,1.000724,1.000299
318809,57674.99,57684.21,57525.00,57540.40,-1.182926,88.831368,5.116978e+06,4682,36.346760,2.094020e+06,1.000299,0.999959,0.997832,0.997666
318810,57540.40,57595.72,57498.56,57578.08,2.578556,109.076746,6.275271e+06,4631,39.890115,2.295065e+06,0.997666,0.998466,0.999540,1.000655
318811,57576.01,57614.06,57546.31,57597.17,3.201796,81.945281,4.718366e+06,4336,34.198034,1.969175e+06,1.000619,1.000318,1.000830,1.000332

In [544]:
ada

,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,Year,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
0,0.25551,0.27000,0.25551,0.26666,268613.33,70602.884982,77,209583.50,55138.269746,2018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,0.26700,0.28800,0.26121,0.26696,1278878.30,342194.004025,567,410305.16,110163.574054,2018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003472
2,0.26698,0.28134,0.26389,0.26709,1372572.09,367736.101426,733,385452.37,103282.211192,2018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006944
3,0.26708,0.26869,0.26208,0.26331,977324.75,260132.114090,437,251076.69,66780.267625,2018,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.010417
4,0.26331,0.26436,0.26008,0.26290,887698.10,232282.163354,591,429640.80,112198.952292,2018,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.013889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,303316.52,405653.768865,731,121599.65,162632.498029,2021,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.711806
318808,1.33700,1.33740,1.33400,1.33570,403303.33,538749.725321,797,132133.12,176544.449839,2021,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.715278
318809,1.33550,1.33590,1.33150,1.33190,374242.62,499010.296564,1013,146257.71,195030.012255,2021,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.718750
318810,1.33190,1.33320,1.33000,1.33280,529332.55,704819.153364,1251,301902.33,402044.918305,2021,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.722222
318811,1.33280,1.33460,1.33250,1.33450,133120.72,177509.742627,246,82977.88,110646.549106,2021,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.725694

In [545]:
ada_hl_co = (ada['High'] - ada['Low'])/(ada['Open'])

In [546]:
ada_hl_co

0         0.056710
1         0.100337
2         0.065361
3         0.024749
4         0.016255
            ...
318807    0.001495
318808    0.002543
318809    0.003295
318810    0.002403
318811    0.001576
Length: 318812, dtype: float64

In [547]:
ada.insert(4, 'HL/O', ada_hl_co)

In [548]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,15m,20m,25m,30m,35m,40m,45m,50m,55m,Time/days
0,0.25551,0.27000,0.25551,0.26666,0.056710,268613.33,70602.884982,77,209583.50,55138.269746,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003472
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006944
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.010417
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.013889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.711806
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.715278
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.718750
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.722222
318811,1.33280,1.33460,1.33250,1.33450,0.001576,133120.72,177509.742627,246,82977.88,110646.549106,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1110.725694

In [549]:
for col in ada.columns[:4]:
    ada.insert(len(ada.columns), col + ' Ratio', ada[col]/ada[col].shift(1))

In [550]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,35m,40m,45m,50m,55m,Time/days,Open Ratio,High Ratio,Low Ratio,Close Ratio
0,0.25551,0.27000,0.25551,0.26666,0.056710,268613.33,70602.884982,77,209583.50,55138.269746,...,0.0,0.0,0.0,0.0,0.0,0.000000,NaN,NaN,NaN,NaN
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,0.0,0.0,0.0,0.0,0.0,0.003472,1.044969,1.066667,1.022308,1.001125
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,0.0,0.0,0.0,0.0,0.0,0.006944,0.999925,0.976875,1.010260,1.000487
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,0.0,0.0,0.0,0.0,0.0,0.010417,1.000375,0.955037,0.993141,0.985847
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,0.0,0.0,0.0,0.0,0.0,0.013889,0.985884,0.983885,0.992369,0.998443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,0.0,0.0,0.0,0.0,0.0,1110.711806,0.999701,0.999701,1.000524,0.999402
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,0.0,0.0,0.0,0.0,0.0,1110.715278,0.999327,0.999477,0.998428,0.999028
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,0.0,0.0,0.0,0.0,0.0,1110.718750,0.998878,0.998878,0.998126,0.997155
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,0.0,0.0,0.0,0.0,0.0,1110.722222,0.997304,0.997979,0.998873,1.000676
318811,1.33280,1.33460,1.33250,1.33450,0.001576,133120.72,177509.742627,246,82977.88,110646.549106,...,0.0,0.0,0.0,0.0,0.0,1110.725694,1.000676,1.001050,1.001880,1.001276

In [551]:
for col in btc.columns:
    ada.insert(len(ada.columns), col, btc[col])

In [552]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC HL/CO,BTC Volume,BTC Quote asset volume,BTC Number of trades,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio
0,0.25551,0.27000,0.25551,0.26666,0.056710,268613.33,70602.884982,77,209583.50,55138.269746,...,-1.531638,148.245567,1.191060e+06,637,70.516715,5.664891e+05,NaN,NaN,NaN,NaN
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,-211.800000,60.944816,4.894450e+05,406,37.350873,2.999910e+05,0.997901,0.998124,1.000026,0.999995
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,-1.277994,79.428218,6.371818e+05,639,42.065398,3.374793e+05,0.999994,0.999770,0.998230,0.997765
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,-3.100000,134.520342,1.078367e+06,697,65.886986,5.283480e+05,0.997765,0.998985,0.998750,0.999002
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,4.678392,51.748348,4.145381e+05,463,22.759268,1.823459e+05,0.999003,0.999401,1.000171,1.000498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,-30.441315,77.757069,4.482218e+06,3466,34.401756,1.982985e+06,0.999651,0.999743,1.001482,0.999963
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,2.119420,119.218784,6.875150e+06,4052,51.587597,2.974936e+06,0.999963,1.000232,1.000724,1.000299
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,-1.182926,88.831368,5.116978e+06,4682,36.346760,2.094020e+06,1.000299,0.999959,0.997832,0.997666
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,2.578556,109.076746,6.275271e+06,4631,39.890115,2.295065e+06,0.997666,0.998466,0.999540,1.000655
318811,1.33280,1.33460,1.33250,1.33450,0.001576,133120.72,177509.742627,246,82977.88,110646.549106,...,3.201796,81.945281,4.718366e+06,4336,34.198034,1.969175e+06,1.000619,1.000318,1.000830,1.000332

In [553]:
ada = ada.drop('BTC HL/CO', axis = 1)

In [554]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Close,BTC Volume,BTC Quote asset volume,BTC Number of trades,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio
0,0.25551,0.27000,0.25551,0.26666,0.056710,268613.33,70602.884982,77,209583.50,55138.269746,...,8032.99,148.245567,1.191060e+06,637,70.516715,5.664891e+05,NaN,NaN,NaN,NaN
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,8032.95,60.944816,4.894450e+05,406,37.350873,2.999910e+05,0.997901,0.998124,1.000026,0.999995
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,8015.00,79.428218,6.371818e+05,639,42.065398,3.374793e+05,0.999994,0.999770,0.998230,0.997765
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,8007.00,134.520342,1.078367e+06,697,65.886986,5.283480e+05,0.997765,0.998985,0.998750,0.999002
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,8010.99,51.748348,4.145381e+05,463,22.759268,1.823459e+05,0.999003,0.999401,1.000171,1.000498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,57657.75,77.757069,4.482218e+06,3466,34.401756,1.982985e+06,0.999651,0.999743,1.001482,0.999963
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,57675.00,119.218784,6.875150e+06,4052,51.587597,2.974936e+06,0.999963,1.000232,1.000724,1.000299
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,57540.40,88.831368,5.116978e+06,4682,36.346760,2.094020e+06,1.000299,0.999959,0.997832,0.997666
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,57578.08,109.076746,6.275271e+06,4631,39.890115,2.295065e+06,0.997666,0.998466,0.999540,1.000655
318811,1.33280,1.33460,1.33250,1.33450,0.001576,133120.72,177509.742627,246,82977.88,110646.549106,...,57597.17,81.945281,4.718366e+06,4336,34.198034,1.969175e+06,1.000619,1.000318,1.000830,1.000332

In [555]:
btc_hl_co = (ada['BTC High'] - ada['BTC Low'])/(ada['BTC Open'])

In [556]:
ada.insert(len(ada.columns), 'BTC HL/O', btc_hl_co)

In [557]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Volume,BTC Quote asset volume,BTC Number of trades,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O
0,0.25551,0.27000,0.25551,0.26666,0.056710,268613.33,70602.884982,77,209583.50,55138.269746,...,148.245567,1.191060e+06,637,70.516715,5.664891e+05,NaN,NaN,NaN,NaN,0.003217
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,60.944816,4.894450e+05,406,37.350873,2.999910e+05,0.997901,0.998124,1.000026,0.999995,0.001318
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,79.428218,6.371818e+05,639,42.065398,3.374793e+05,0.999994,0.999770,0.998230,0.997765,0.002856
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,134.520342,1.078367e+06,697,65.886986,5.283480e+05,0.997765,0.998985,0.998750,0.999002,0.003094
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,51.748348,4.145381e+05,463,22.759268,1.823459e+05,0.999003,0.999401,1.000171,1.000498,0.002325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,77.757069,4.482218e+06,3466,34.401756,1.982985e+06,0.999651,0.999743,1.001482,0.999963,0.001125
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,119.218784,6.875150e+06,4052,51.587597,2.974936e+06,0.999963,1.000232,1.000724,1.000299,0.000634
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,88.831368,5.116978e+06,4682,36.346760,2.094020e+06,1.000299,0.999959,0.997832,0.997666,0.002760
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,109.076746,6.275271e+06,4631,39.890115,2.295065e+06,0.997666,0.998466,0.999540,1.000655,0.001689
318811,1.33280,1.33460,1.33250,1.33450,0.001576,133120.72,177509.742627,246,82977.88,110646.549106,...,81.945281,4.718366e+06,4336,34.198034,1.969175e+06,1.000619,1.000318,1.000830,1.000332,0.001177

In [558]:
ada_spec

[20136,
 20436,
 22280,
 53072,
 60470,
 94370,
 112742,
 119465,
 139094,
 164918,
 168346,
 190210,
 193194,
 197129,
 211991,
 230393,
 275039,
 281173,
 282133,
 295966,
 302554,
 315496,
 316931]

In [559]:
for row in ada_spec:
    ada = ada.drop(row, axis = 0)

In [560]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Volume,BTC Quote asset volume,BTC Number of trades,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O
0,0.25551,0.27000,0.25551,0.26666,0.056710,268613.33,70602.884982,77,209583.50,55138.269746,...,148.245567,1.191060e+06,637,70.516715,5.664891e+05,NaN,NaN,NaN,NaN,0.003217
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,60.944816,4.894450e+05,406,37.350873,2.999910e+05,0.997901,0.998124,1.000026,0.999995,0.001318
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,79.428218,6.371818e+05,639,42.065398,3.374793e+05,0.999994,0.999770,0.998230,0.997765,0.002856
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,134.520342,1.078367e+06,697,65.886986,5.283480e+05,0.997765,0.998985,0.998750,0.999002,0.003094
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,51.748348,4.145381e+05,463,22.759268,1.823459e+05,0.999003,0.999401,1.000171,1.000498,0.002325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,77.757069,4.482218e+06,3466,34.401756,1.982985e+06,0.999651,0.999743,1.001482,0.999963,0.001125
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,119.218784,6.875150e+06,4052,51.587597,2.974936e+06,0.999963,1.000232,1.000724,1.000299,0.000634
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,88.831368,5.116978e+06,4682,36.346760,2.094020e+06,1.000299,0.999959,0.997832,0.997666,0.002760
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,109.076746,6.275271e+06,4631,39.890115,2.295065e+06,0.997666,0.998466,0.999540,1.000655,0.001689
318811,1.33280,1.33460,1.33250,1.33450,0.001576,133120.72,177509.742627,246,82977.88,110646.549106,...,81.945281,4.718366e+06,4336,34.198034,1.969175e+06,1.000619,1.000318,1.000830,1.000332,0.001177

In [561]:
ada['OHLC'] = (ada['Open'] + ada['High'] + ada['Low'] + ada['Close'])/4

In [562]:
ada['BTC OHLC'] = (ada['BTC Open'] + ada['BTC High'] + ada['BTC Low'] + ada['BTC Close'])/4

In [563]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Number of trades,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O,OHLC,BTC OHLC
0,0.25551,0.27000,0.25551,0.26666,0.056710,268613.33,70602.884982,77,209583.50,55138.269746,...,637,70.516715,5.664891e+05,NaN,NaN,NaN,NaN,0.003217,0.261920,8039.1975
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,406,37.350873,2.999910e+05,0.997901,0.998124,1.000026,0.999995,0.001318,0.270792,8031.2400
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,639,42.065398,3.374793e+05,0.999994,0.999770,0.998230,0.997765,0.002856,0.269825,8022.7275
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,697,65.886986,5.283480e+05,0.997765,0.998985,0.998750,0.999002,0.003094,0.265290,8011.7000
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,463,22.759268,1.823459e+05,0.999003,0.999401,1.000171,1.000498,0.002325,0.262663,8009.8400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,3466,34.401756,1.982985e+06,0.999651,0.999743,1.001482,0.999963,0.001125,1.337275,57649.7825
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,4052,51.587597,2.974936e+06,0.999963,1.000232,1.000724,1.000299,0.000634,1.336025,57667.3325
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,4682,36.346760,2.094020e+06,1.000299,0.999959,0.997832,0.997666,0.002760,1.333700,57606.1500
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,4631,39.890115,2.295065e+06,0.997666,0.998466,0.999540,1.000655,0.001689,1.331975,57553.1900
318811,1.33280,1.33460,1.33250,1.33450,0.001576,133120.72,177509.742627,246,82977.88,110646.549106,...,4336,34.198034,1.969175e+06,1.000619,1.000318,1.000830,1.000332,0.001177,1.333600,57583.3875

In [564]:
ada['Delta T'] = (ada['Time/days'] - ada['Time/days'].shift(1))

In [565]:
ada = ada.drop('Time/days', axis = 1)

In [566]:
ada = ada.dropna()

In [569]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O,OHLC,BTC OHLC,Delta T
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,37.350873,2.999910e+05,0.997901,0.998124,1.000026,0.999995,0.001318,0.270792,8031.2400,0.003472
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,42.065398,3.374793e+05,0.999994,0.999770,0.998230,0.997765,0.002856,0.269825,8022.7275,0.003472
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,65.886986,5.283480e+05,0.997765,0.998985,0.998750,0.999002,0.003094,0.265290,8011.7000,0.003472
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,22.759268,1.823459e+05,0.999003,0.999401,1.000171,1.000498,0.002325,0.262663,8009.8400,0.003472
5,0.26290,0.26496,0.26100,0.26301,0.015063,693072.58,182547.453941,322,286904.98,75550.059123,...,67.149970,5.373307e+05,1.000310,0.999383,0.998954,1.000290,0.002752,0.262968,8007.7100,0.003472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,34.401756,1.982985e+06,0.999651,0.999743,1.001482,0.999963,0.001125,1.337275,57649.7825,0.003472
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,51.587597,2.974936e+06,0.999963,1.000232,1.000724,1.000299,0.000634,1.336025,57667.3325,0.003472
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,36.346760,2.094020e+06,1.000299,0.999959,0.997832,0.997666,0.002760,1.333700,57606.1500,0.003472
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,39.890115,2.295065e+06,0.997666,0.998466,0.999540,1.000655,0.001689,1.331975,57553.1900,0.003472
318811,1.33280,1.33460,1.33250,1.33450,0.001576,133120.72,177509.742627,246,82977.88,110646.549106,...,34.198034,1.969175e+06,1.000619,1.000318,1.000830,1.000332,0.001177,1.333600,57583.3875,0.003472

In [567]:
ret = 100*(ada['Close'] - ada['Open'])/ada['Open']

In [568]:
ret

1        -0.014981
2         0.041202
3        -1.411562
4        -0.155710
5         0.041841
            ...
318807   -0.067270
318808   -0.097233
318809   -0.269562
318810    0.067573
318811    0.127551
Length: 318788, dtype: float64

In [571]:
ret = ret.shift(-1)

In [573]:
ret = ret.dropna()

In [574]:
ret.to_csv('ada_return.csv')

In [492]:
ada = ada.iloc[:-1]

In [494]:
ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O,OHLC,BTC OHLC,Delta T
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,37.350873,2.999910e+05,0.997901,0.998124,1.000026,0.999995,0.001318,0.270792,8031.2400,0.003472
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,42.065398,3.374793e+05,0.999994,0.999770,0.998230,0.997765,0.002856,0.269825,8022.7275,0.003472
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,65.886986,5.283480e+05,0.997765,0.998985,0.998750,0.999002,0.003094,0.265290,8011.7000,0.003472
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,22.759268,1.823459e+05,0.999003,0.999401,1.000171,1.000498,0.002325,0.262663,8009.8400,0.003472
5,0.26290,0.26496,0.26100,0.26301,0.015063,693072.58,182547.453941,322,286904.98,75550.059123,...,67.149970,5.373307e+05,1.000310,0.999383,0.998954,1.000290,0.002752,0.262968,8007.7100,0.003472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318806,1.33830,1.33850,1.33540,1.33780,0.002316,328013.22,438545.625470,848,180820.69,241771.521312,...,57.395614,3.305860e+06,0.999480,0.999334,0.997799,0.999651,0.002859,1.337500,57637.7450,0.003472
318807,1.33790,1.33810,1.33610,1.33700,0.001495,303316.52,405653.768865,731,121599.65,162632.498029,...,34.401756,1.982985e+06,0.999651,0.999743,1.001482,0.999963,0.001125,1.337275,57649.7825,0.003472
318808,1.33700,1.33740,1.33400,1.33570,0.002543,403303.33,538749.725321,797,132133.12,176544.449839,...,51.587597,2.974936e+06,0.999963,1.000232,1.000724,1.000299,0.000634,1.336025,57667.3325,0.003472
318809,1.33550,1.33590,1.33150,1.33190,0.003295,374242.62,499010.296564,1013,146257.71,195030.012255,...,36.346760,2.094020e+06,1.000299,0.999959,0.997832,0.997666,0.002760,1.333700,57606.1500,0.003472
318810,1.33190,1.33320,1.33000,1.33280,0.002403,529332.55,704819.153364,1251,301902.33,402044.918305,...,39.890115,2.295065e+06,0.997666,0.998466,0.999540,1.000655,0.001689,1.331975,57553.1900,0.003472

In [495]:
train_ada = ada.head(2*ada.shape[0]//5)

In [496]:
train_ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O,OHLC,BTC OHLC,Delta T
1,0.26700,0.28800,0.26121,0.26696,0.100337,1278878.30,342194.004025,567,410305.16,110163.574054,...,37.350873,299991.019616,0.997901,0.998124,1.000026,0.999995,0.001318,0.270792,8031.2400,0.003472
2,0.26698,0.28134,0.26389,0.26709,0.065361,1372572.09,367736.101426,733,385452.37,103282.211192,...,42.065398,337479.287939,0.999994,0.999770,0.998230,0.997765,0.002856,0.269825,8022.7275,0.003472
3,0.26708,0.26869,0.26208,0.26331,0.024749,977324.75,260132.114090,437,251076.69,66780.267625,...,65.886986,528347.962287,0.997765,0.998985,0.998750,0.999002,0.003094,0.265290,8011.7000,0.003472
4,0.26331,0.26436,0.26008,0.26290,0.016255,887698.10,232282.163354,591,429640.80,112198.952292,...,22.759268,182345.907651,0.999003,0.999401,1.000171,1.000498,0.002325,0.262663,8009.8400,0.003472
5,0.26290,0.26496,0.26100,0.26301,0.015063,693072.58,182547.453941,322,286904.98,75550.059123,...,67.149970,537330.655735,1.000310,0.999383,0.998954,1.000290,0.002752,0.262968,8007.7100,0.003472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127518,0.07683,0.07689,0.07667,0.07688,0.002863,207622.50,15947.178259,48,81251.70,6241.608935,...,78.645959,864282.221571,0.999848,0.999055,1.002027,1.001205,0.004114,0.076817,11000.6200,0.003472
127519,0.07688,0.07698,0.07687,0.07698,0.001431,95889.80,7373.235657,18,93458.80,7186.170207,...,44.121870,487044.646563,1.001366,1.004009,1.004040,1.001336,0.004094,0.076927,11030.1775,0.003472
127520,0.07695,0.07695,0.07677,0.07685,0.002339,130532.80,10029.701658,32,58964.10,4530.611225,...,47.246696,520094.653510,1.001126,0.997340,0.998044,0.996954,0.003375,0.076880,11012.1400,0.003472
127521,0.07680,0.07689,0.07673,0.07685,0.002083,46493.40,3570.548809,27,23257.70,1786.956205,...,50.697320,558801.481705,0.997526,1.000833,1.000082,1.003875,0.004136,0.076817,11018.4925,0.003472
127522,0.07686,0.07686,0.07669,0.07669,0.002212,65935.10,5059.999996,22,20380.10,1564.921174,...,36.481913,401534.771613,1.003178,1.000909,0.998884,0.994806,0.006145,0.076775,11012.3425,0.003472

In [497]:
from sklearn.preprocessing import StandardScaler

In [498]:
scaler = StandardScaler()

In [499]:
scaler.fit(train_ada)

StandardScaler()

In [500]:
final_ada = scaler.transform(ada)

In [501]:
df_ada = pd.DataFrame(final_ada, columns = ada.columns)

In [502]:
df_ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O,OHLC,BTC OHLC,Delta T
0,2.282852,2.562734,2.212629,2.282406,24.819483,0.995053,4.294496,3.389996,0.357925,2.383868,...,-0.392947,-0.232649,-0.984746,-0.959240,0.010111,-0.004484,-0.495216,2.335417,0.935985,-0.006947
1,2.282575,2.470905,2.249791,2.284203,15.754980,1.121216,4.668924,4.654881,0.293500,2.191511,...,-0.333239,-0.169698,-0.005135,-0.119600,-0.838953,-1.045270,0.107837,2.322039,0.931695,-0.006947
2,2.283958,2.296485,2.224692,2.231937,5.230057,0.588997,3.091531,2.399424,-0.054835,1.171159,...,-0.031545,0.150811,-1.047993,-0.519800,-0.593116,-0.468097,0.201372,2.259333,0.926137,-0.006947
3,2.231832,2.236782,2.196960,2.226268,3.028608,0.468311,2.683271,3.572871,0.408048,2.440763,...,-0.577746,-0.430200,-0.468763,-0.307955,0.078704,0.230459,-0.100163,2.223003,0.925199,-0.006947
4,2.226163,2.245055,2.209717,2.227789,2.719729,0.206239,1.954198,1.523149,0.038041,1.416304,...,-0.015550,0.165895,0.142732,-0.317046,-0.496846,0.133030,0.067042,2.227220,0.924126,-0.006947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318782,17.095265,17.047189,17.107858,17.088891,-0.583635,-0.285330,5.706938,5.531156,-0.236956,6.062752,...,-0.139086,4.814841,-0.245427,-0.342156,-1.042999,-0.164912,0.109068,17.084864,25.938084,-0.006947
318783,17.089734,17.041674,17.117564,17.077830,-0.796534,-0.318585,5.224768,4.639641,-0.390472,3.850551,...,-0.430297,2.593454,-0.165470,-0.133287,0.698270,-0.019404,-0.571228,17.081753,25.944151,-0.006947
318784,17.077291,17.032022,17.088445,17.059855,-0.524900,-0.183948,7.175855,5.142547,-0.363166,4.239436,...,-0.212643,4.259150,-0.019510,0.116437,0.339812,0.137501,-0.763602,17.064469,25.952996,-0.006947
318785,17.056551,17.011340,17.053779,17.007312,-0.330105,-0.223080,6.593305,6.788421,-0.326552,4.756170,...,-0.405664,2.779906,0.137714,-0.022991,-1.027499,-1.091588,0.070468,17.032322,25.922159,-0.006947
318786,17.006775,16.974112,17.032979,17.019756,-0.561293,-0.014244,9.610307,8.601930,0.076918,10.542932,...,-0.360788,3.117503,-1.094347,-0.784859,-0.219575,0.303529,-0.349990,17.008470,25.895467,-0.006947

In [503]:
df_ada.describe()

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O,OHLC,BTC OHLC,Delta T
count,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,...,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000,318787.000000
mean,0.998056,0.998727,0.997294,0.998155,-0.023789,0.614353,3.511681,2.398884,0.573915,3.319774,...,0.337486,1.696656,0.001990,0.002050,0.002064,0.001992,0.085410,0.998065,3.352622,-0.001580
std,4.012962,4.014724,4.010852,4.013165,1.085930,2.268463,16.346380,9.267697,2.227219,15.883615,...,1.558244,4.887575,1.113864,1.081184,1.123044,1.112420,1.151434,4.012933,6.667987,0.777251
min,-1.155680,-1.148210,-1.164690,-1.155673,-1.183948,-0.727015,-0.721810,-0.930422,-0.705689,-0.695574,...,-0.865985,-0.736397,-47.727915,-39.286721,-56.948191,-47.735331,-1.012322,-1.153224,-1.517673,-0.006947
25%,-0.784022,-0.784202,-0.783778,-0.784004,-0.647506,-0.432078,-0.518439,-0.526574,-0.453565,-0.525620,...,-0.412848,-0.307540,-0.390692,-0.363799,-0.302952,-0.389339,-0.513529,-0.784041,0.195777,-0.006947
50%,-0.309079,-0.309476,-0.308851,-0.309047,-0.314524,-0.079165,-0.159731,-0.084626,-0.100875,-0.172775,...,-0.084409,0.146015,0.000145,-0.022355,0.031079,-0.000544,-0.214439,-0.309081,1.258786,-0.006947
75%,0.465624,0.466659,0.465175,0.465817,0.239880,0.755305,0.904031,1.187878,0.701908,0.853902,...,0.499500,1.363066,0.395428,0.311956,0.366051,0.395689,0.292855,0.465788,2.362107,-0.006947
max,20.101855,20.079893,19.944939,20.101652,52.303772,90.475699,1358.523630,740.497646,100.033482,1252.233392,...,61.949121,241.092655,86.244020,59.466192,46.853600,86.025733,76.719466,20.010328,29.456650,188.032774

In [504]:
df_ada.to_csv('Clean_ADA.csv')

In [575]:
df_ada

,Open,High,Low,Close,HL/O,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volumne,...,BTC Taker buy base asset volume,BTC Taker buy quote asset volumne,BTC Open Ratio,BTC High Ratio,BTC Low Ratio,BTC Close Ratio,BTC HL/O,OHLC,BTC OHLC,Delta T
0,2.282852,2.562734,2.212629,2.282406,24.819483,0.995053,4.294496,3.389996,0.357925,2.383868,...,-0.392947,-0.232649,-0.984746,-0.959240,0.010111,-0.004484,-0.495216,2.335417,0.935985,-0.006947
1,2.282575,2.470905,2.249791,2.284203,15.754980,1.121216,4.668924,4.654881,0.293500,2.191511,...,-0.333239,-0.169698,-0.005135,-0.119600,-0.838953,-1.045270,0.107837,2.322039,0.931695,-0.006947
2,2.283958,2.296485,2.224692,2.231937,5.230057,0.588997,3.091531,2.399424,-0.054835,1.171159,...,-0.031545,0.150811,-1.047993,-0.519800,-0.593116,-0.468097,0.201372,2.259333,0.926137,-0.006947
3,2.231832,2.236782,2.196960,2.226268,3.028608,0.468311,2.683271,3.572871,0.408048,2.440763,...,-0.577746,-0.430200,-0.468763,-0.307955,0.078704,0.230459,-0.100163,2.223003,0.925199,-0.006947
4,2.226163,2.245055,2.209717,2.227789,2.719729,0.206239,1.954198,1.523149,0.038041,1.416304,...,-0.015550,0.165895,0.142732,-0.317046,-0.496846,0.133030,0.067042,2.227220,0.924126,-0.006947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318782,17.095265,17.047189,17.107858,17.088891,-0.583635,-0.285330,5.706938,5.531156,-0.236956,6.062752,...,-0.139086,4.814841,-0.245427,-0.342156,-1.042999,-0.164912,0.109068,17.084864,25.938084,-0.006947
318783,17.089734,17.041674,17.117564,17.077830,-0.796534,-0.318585,5.224768,4.639641,-0.390472,3.850551,...,-0.430297,2.593454,-0.165470,-0.133287,0.698270,-0.019404,-0.571228,17.081753,25.944151,-0.006947
318784,17.077291,17.032022,17.088445,17.059855,-0.524900,-0.183948,7.175855,5.142547,-0.363166,4.239436,...,-0.212643,4.259150,-0.019510,0.116437,0.339812,0.137501,-0.763602,17.064469,25.952996,-0.006947
318785,17.056551,17.011340,17.053779,17.007312,-0.330105,-0.223080,6.593305,6.788421,-0.326552,4.756170,...,-0.405664,2.779906,0.137714,-0.022991,-1.027499,-1.091588,0.070468,17.032322,25.922159,-0.006947
318786,17.006775,16.974112,17.032979,17.019756,-0.561293,-0.014244,9.610307,8.601930,0.076918,10.542932,...,-0.360788,3.117503,-1.094347,-0.784859,-0.219575,0.303529,-0.349990,17.008470,25.895467,-0.006947